### ISSUE TITLE
Emojis don't show on Windows

### ISSUE THREAD

**Issue by biscaryn** [thekelvinliu/country-code-emoji#3]
![image](https://user-images.githubusercontent.com/33936909/66258385-7841bf80-e79c-11e9-8190-cb4d2b775b0d.png)

I am using a Windows machine on the latest version of Windows 10, and the emojis don't show.

**Comment by thekelvinliu** [comment]
i can repro this on my windows desktop too. it happens because the microsoft emoji font still doesn't support country flags... in 2019 😒 what you're seeing is expected -- take a look at https://emojipedia.org/flags/ to confirm. if you're building a website, fall back to an image on windows browsers. closing bc not an issue w this library 😄
